import { AiFillStar } from "react-icons/ai";

const data = [
  {
    img: "https://m.media-amazon.com/images/I/61fb9VvP3sL._AC_SX679_.jpg",
    title: "Nike Air Monarch IV",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Nike",
    color: "white",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/71TM0-jUkRL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
    title: "Nike Air Vapormax Plus",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Nike",
    color: "red",
    category: "sneakers",
  },

  {
    img: "https://m.media-amazon.com/images/I/71D28eKVBcL._AC_SX679_.jpg",
    title: "Nike Waffle One Sneaker",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Nike",
    color: "green",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/71i-hhf2vkL._AC_SX679_.jpg",
    title: "Nike Running Shoe",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Adidas",
    color: "black",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/71j3QRu047L._AC_SX679_.jpg",
    title: "Flat Slip On Pumps",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Vans",
    color: "green",
    category: "flats",
  },
  {
    img: "https://m.media-amazon.com/images/I/719TNGokYTL._AC_SX679_.jpg",
    title: "Knit Ballet Flat",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Adidas",
    color: "black",
    category: "flats",
  },

  {
    img: "https://m.media-amazon.com/images/I/71JOqW7LgRL._AC_SX679_.jpg",
    title: "Loafer Flats",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Vans",
    color: "white",
    category: "flats",
  },

  {
    img: "https://m.media-amazon.com/images/I/71S1zCWUkBL._AC_SX679_.jpg",
    title: "Nike Zoom Freak",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Nike",
    color: "green",
    category: "sneakers",
  },

  {
    img: "https://m.media-amazon.com/images/I/71jDS5VoNML._AC_SX679_.jpg",
    title: "Nike Men's Sneaker",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Adidas",
    color: "blue",
    category: "sneakers",
  },

  {
    img: "https://m.media-amazon.com/images/I/71HGi4ozLtL._AC_SX679_.jpg",
    title: "PUMA BLACK-OCE",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Puma",
    color: "green",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/71LY3OBW38L._AC_SX679_.jpg",
    title: "Pacer Future Sneaker",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Puma",
    color: "red",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/710XW3xBDiL._AC_SX679_.jpg",
    title: "Unisex-Adult Super",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Puma",
    color: "black",
    category: "sneakers",
  },
];

export default data;